---
title: "DESeq2_NO_OUTLIER_TEcount_dm6_forStrand_analysis"
author: "Benjamin McMichael"
date: "08/09/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(DESeq2)
library(dplyr)
library(tidyr)
library(ggplot2)
library(pheatmap)
library(EnhancedVolcano)
library(AnnotationDbi)
library(org.Dm.eg.db)
library(purrr)

setwd("/work/users/b/d/bdmcmi/Benjamin/flyHead_analysis/Paper_Analysis_V2/TE_Analysis/TEcounts/TEcount_multi_forStrand")
currentDate <- Sys.Date() %>% format("%Y%m%d")

```

```{r}
### Join TE Counts into TEcount Table ####

files_to_read <- list.files(pattern = "*.cntTable", full.names = T)
files_to_read

all_files <- lapply(files_to_read, function(x) {
   read.table(file = x, 
              header = TRUE)
}) 

TEcount_Table <- reduce(all_files, full_join, by = "gene.TE") %>%
                    tibble::column_to_rownames(var = "gene.TE")
min_read <- 1
TEcount_Table <- TEcount_Table[apply(TEcount_Table,1,function(x){max(x)}) > min_read,]

TEcount_Table_NO_OUTLIER <- TEcount_Table[,c(1:13, 15:24)]
colnames(TEcount_Table_NO_OUTLIER) <- sapply(colnames(TEcount_Table_NO_OUTLIER), substr, 0,20)

```

```{r}
# Read in sample info

sampleInfo_NO_OUTLIER <- read.csv("sample_info_NO_OUTLIER.txt")
sampleInfo_NO_OUTLIER <- DataFrame(sampleInfo_NO_OUTLIER)

```

```{r}
# Check sample order

colnames(TEcount_Table_NO_OUTLIER)
rownames(sampleInfo_NO_OUTLIER) 
all(rownames(sampleInfo_NO_OUTLIER) == colnames(TEcount_Table_NO_OUTLIER))

#all(sampleInfo_NO_OUTLIER$run == colnames(TEcount_Table_NO_OUTLIER))

```

```{r}
### NO Interaction Model ####

sampleInfo_NO_OUTLIER_age_geno <- sampleInfo_NO_OUTLIER
age_geno <- factor(c("young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "young_K36R", "old_K36R", "old_K36R",
                  "young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "old_K36R", "old_K36R",
                  "young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "young_K36R", "old_K36R", "old_K36R")
                            )
sampleInfo_NO_OUTLIER_age_geno$age_geno <- age_geno

dds <- DESeqDataSetFromMatrix(countData = TEcount_Table_NO_OUTLIER, colData = sampleInfo_NO_OUTLIER_age_geno, design = ~ sex + age_geno)
dds$age_geno = relevel(dds$age_geno, "young_Adel")
dds <- DESeq(dds)

```

```{r}
# Export normalized counts

normCounts <- counts(dds, normalized=T)
write.csv(as.data.frame(normCounts), 
          file = paste0("DESeq2_",currentDate,"_noINT_noOUT_TEcount_dm6_forStrand_normCounts.csv"))

```

```{r}
# youngFly Results

youngFly_res <- results(dds, contrast = c("age_geno", "young_K36R", "young_Adel"))
summary(youngFly_res, 0.05)

```

```{r}
# This adds extra columns with gene id and descriptions

youngFly_res$symbol <- mapIds(org.Dm.eg.db, keys=row.names(youngFly_res), column="SYMBOL", keytype="FLYBASE", multiVals="first")
youngFly_res$name <- mapIds(org.Dm.eg.db, keys=row.names(youngFly_res), column="GENENAME", keytype="FLYBASE", multiVals="first")

```

```{r}
# Volcano plot

png(filename = paste0("youngFly_TEcount_dm6_forStrand_volcanoPlot_",currentDate,".png"), 
    units = "in",
    width = 9, 
    height = 6, 
    res = 500)

EnhancedVolcano(youngFly_res,
                lab = rownames(youngFly_res),
                selectLab = c(""),
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.05,
                legendPosition = 'right',
                legendLabels=c('Not sig.','Log2 FC','p-value',
                               'p-value & Log2 FC'),
                title = "Young Fly Differential TEcount Expression: Gene",
                legendLabSize = 16,
                legendIconSize = 5.0)

dev.off()

```

```{r}
# Volcano plot: Young Fly TE Specific

youngFly_res_df <- data.frame(youngFly_res) %>%
  tibble::rownames_to_column("Gene")

youngFly_res_TE <- youngFly_res_df %>%
  filter(!grepl("FBgn", Gene))

png(filename = paste0("youngFly_TEcount_dm6_forStrand_TEspecific_volcanoPlot_",currentDate,".png"), 
    units = "in",
    width = 9, 
    height = 6, 
    res = 500)

EnhancedVolcano(youngFly_res_TE,
                lab = youngFly_res_TE$Gene,
                #selectLab = c(""),
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.05,
                legendPosition = 'right',
                legendLabels=c('Not sig.','Log2 FC','p-value',
                               'p-value & Log2 FC'),
                title = "Young Fly Differential TEcount TE Specific Expression: Gene",
                legendLabSize = 16,
                legendIconSize = 5.0)

dev.off()

```

```{r}
# Count number of significantly up and down genes (by adjusted p-value) that correspond to MA-plots and Venn diagrams

youngFly_sigCount_padj <- youngFly_res %>%
                        data.frame() %>%
                        dplyr::filter(padj < 0.05) %>% 
                        #dplyr::filter(log2FoldChange > 1 | log2FoldChange < -1) %>%
                        dplyr::mutate(Enrichment = ifelse(log2FoldChange > 0, 'Up', 'Down'))
table(youngFly_sigCount_padj['Enrichment'])

```

```{r}
# Export significant counts by adjusted p-value

youngFly_sigCount_padj %>%
  write.csv(., file = paste0("DESeq2_",currentDate,"_youngFly_noINT_noOUT_TEcount_dm6_forStrand_padj_sigCounts.csv")
  )

```

```{r}
# Count number of significantly up and down genes (by adjusted p-value and LFC) that correspond to MA-plots and Venn diagrams

youngFly_sigCount_padjLFC <- youngFly_res %>%
  data.frame() %>%
  dplyr::filter(padj < 0.05) %>% 
  dplyr::filter(log2FoldChange > 1 | log2FoldChange < -1) %>%
  dplyr::mutate(Enrichment = ifelse(log2FoldChange > 1, 'Up', 'Down'))
table(youngFly_sigCount_padjLFC['Enrichment'])

```

```{r}
# Export significant counts by adjusted p-value and LFC

youngFly_sigCount_padjLFC %>%
  write.csv(., file = paste0("DESeq2_",currentDate,"_youngFly_noINT_noOUT_TEcount_dm6_forStrand_padjLFC_sigCounts.csv")
  )

```

```{r}
# Export full youngFly results

youngFly_resOrdered <- youngFly_res[order(youngFly_res$padj),]
write.csv(as.data.frame(youngFly_resOrdered), 
          file = paste0("DESeq2_",currentDate,"_youngFly_noINT_noOUT_TEcount_dm6_forStrand_res.csv"))

```

```{r}
# oldFly Results

oldFly_res <- results(dds, contrast = c("age_geno", "old_K36R", "old_Adel"))
summary(oldFly_res, 0.05)

```

```{r}
# This adds extra columns with gene id and descriptions

oldFly_res$symbol <- mapIds(org.Dm.eg.db, keys=row.names(oldFly_res), column="SYMBOL", keytype="FLYBASE", multiVals="first")
oldFly_res$name <- mapIds(org.Dm.eg.db, keys=row.names(oldFly_res), column="GENENAME", keytype="FLYBASE", multiVals="first")

```

```{r}
# Volcano plot

png(filename = paste0("oldFly_TEcount_dm6_forStrand_volcanoPlot_",currentDate,".png"), 
    units = "in",
    width = 9, 
    height = 6, 
    res = 500)

EnhancedVolcano(oldFly_res,
                lab = rownames(oldFly_res),
                selectLab = c(""),
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.05,
                legendPosition = 'right',
                legendLabels=c('Not sig.','Log2 FC','p-value',
                               'p-value & Log2 FC'),
                title = "Old Fly Differential TEcount Expression: Gene",
                legendLabSize = 16,
                legendIconSize = 5.0)

dev.off()

```

```{r}
# Volcano plot: Old Fly TE Specific

oldFly_res_df <- data.frame(oldFly_res) %>%
  tibble::rownames_to_column("Gene")

oldFly_res_TE <- oldFly_res_df %>%
  filter(!grepl("FBgn", Gene))

png(filename = paste0("oldFly_TEcount_dm6_forStrand_TEspecific_volcanoPlot_",currentDate,".png"), 
    units = "in",
    width = 9, 
    height = 6, 
    res = 500)

EnhancedVolcano(oldFly_res_TE,
                lab=oldFly_res_TE$Gene,
                selectLab = c(""),
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.05,
                legendPosition = 'right',
                legendLabels=c('Not sig.','Log2 FC','p-value',
                               'p-value & Log2 FC'),
                title = "Old Fly Differential TEcount TE Specific Expression: Gene",
                legendLabSize = 16,
                legendIconSize = 5.0)
dev.off()

```

```{r}
# Volcano plot: Old Fly TE Specific w/ LTR Labeled

LTR_list <- oldFly_res_TE[grepl("LTR", oldFly_res_TE$Gene),]

# create custom key-value pairs for different cell-types
# this can be achieved with an ifelse statements
keyvals.shape <- ifelse(
  oldFly_res_TE$Gene %in% LTR_list$Gene, 17, 16)

keyvals.shape[is.na(keyvals.shape)] <- 16
names(keyvals.shape)[keyvals.shape == 16] <- 'Non-LTR Elements'
names(keyvals.shape)[keyvals.shape == 17] <- 'LTR Elements'

png(filename = paste0("oldFly_TEcount_dm6_forStrand_TEspecific_LTRlabeled_volcanoPlot_",currentDate,".png"), 
    units = "in",
    width = 9, 
    height = 6, 
    res = 500)

EnhancedVolcano(oldFly_res_TE,
                lab = oldFly_res_TE$Gene,
                selectLab = c(""),
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.05,
                shapeCustom = keyvals.shape,
                legendPosition = 'right',
                legendLabels=c('Not sig.','Log2 FC','p-value',
                               'p-value & Log2 FC'),
                title = "Old Fly Differential TEcount Expression: Gene",
                legendLabSize = 16,
                legendIconSize = 5.0)

dev.off()

```

```{r}
# Count number of significantly up and down genes (by adjusted p-value) that correspond to MA-plots and Venn diagrams

oldFly_sigCount_padj <- oldFly_res %>%
  data.frame() %>%
  dplyr::filter(padj < 0.05) %>% 
  #dplyr::filter(log2FoldChange > 1 | log2FoldChange < -1) %>%
  dplyr::mutate(Enrichment = ifelse(log2FoldChange > 0, 'Up', 'Down'))
table(oldFly_sigCount_padj['Enrichment'])

```

```{r}
# Export significant counts by adjusted p-value

oldFly_sigCount_padj %>%
  write.csv(., file = paste0("DESeq2_",currentDate,"_oldFly_noINT_noOUT_TEcount_dm6_forStrand_padj_sigCounts.csv")
  )

```

```{r}
# Count number of significantly up and down genes (by adjusted p-value and LFC) that correspond to MA-plots and Venn diagrams

oldFly_sigCount_padjLFC <- oldFly_res %>%
  data.frame() %>%
  dplyr::filter(padj < 0.05) %>% 
  dplyr::filter(log2FoldChange > 1 | log2FoldChange < -1) %>%
  dplyr::mutate(Enrichment = ifelse(log2FoldChange > 1, 'Up', 'Down'))
table(oldFly_sigCount_padjLFC['Enrichment'])

```

```{r}
# Export significant counts by adjusted p-value and LFC

oldFly_sigCount_padjLFC %>%
  write.csv(., file = paste0("DESeq2_",currentDate,"_oldFly_noINT_noOUT_TEcount_dm6_forStrand_padjLFC_sigCounts.csv")
  )

```

```{r}
# Export full oldFly results

oldFly_resOrdered <- oldFly_res[order(oldFly_res$padj),]
write.csv(as.data.frame(oldFly_resOrdered), 
          file = paste0("DESeq2_",currentDate,"_oldFly_noINT_noOUT_TEcount_dm6_forStrand_res.csv"))

```
