---
title: "DESeq2_BM_forStrand_NO_OUTLIER_08292023"
author: "Benjamin McMichael"
date: "8/29/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(DESeq2)
library(dplyr)
library(tidyr)
library(ggplot2)
library(pheatmap)
library(EnhancedVolcano)
library(AnnotationDbi)
library(org.Dm.eg.db)

setwd("/work/users/b/d/bdmcmi/Benjamin/flyHead_analysis/Paper_Analysis_V2/RNA_seq_analysis/DESeq2")
currentDate <- Sys.Date() %>% format("%Y%m%d")

```

```{r}

filteredCounts <- read.table("/work/users/b/d/bdmcmi/Benjamin/flyHead_analysis/Paper_Analysis_V2/RNA_seq_analysis/Counts/featureCounts_sortedByCoord_forStrand.txt", header = TRUE, row.names =1) %>% 
  dplyr::rename("Sample_MATA_LB_JB_70" = "MATA_LB_JB_70.y_Adel_f_ACGTCGTT_S1_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_71" = "MATA_LB_JB_71.y_Adel_m_GTCCTGTT_S2_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_72" = "MATA_LB_JB_72.o_Adel_f_AGAAGCCT_S3_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_73" = "MATA_LB_JB_73.o_Adel_m_GAAGATCC_S4_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_74" = "MATA_LB_JB_74.y_K36_f_TAGCTGAG_S5_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_75" = "MATA_LB_JB_75.y_K36_m_ACGTCCAA_S6_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_76" = "MATA_LB_JB_76.o_K36_f_CACACATC_S7_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_77" = "MATA_LB_JB_77.o_K36_m_CGGATCAA_S8_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_78" = "MATA_LB_JB_78.y_Adel_f_TCAGCCTT_S9_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_79" = "MATA_LB_JB_79.y_Adel_m_AAGGCTCT_S10_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_80" = "MATA_LB_JB_80.o_Adel_f_TGTTCCGT_S11_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_81" = "MATA_LB_JB_81.o_Adel_m_GGAATGTC_S12_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_82" = "MATA_LB_JB_82.y_K36_f_CATCCAAG_S13_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_83" = "MATA_LB_JB_83.y_K36_m_GTCAACAG_S14_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_84" = "MATA_LB_JB_84.o_K36_f_TCGCTATC_S15_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_85" = "MATA_LB_JB_85.o_K36_m_AGCCTATC_S16_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_86" = "MATA_LB_JB_86.y_Adel_f_TCGGATTC_S17_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_87" = "MATA_LB_JB_87.y_Adel_m_CGGAGTAT_S18_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_88" = "MATA_LB_JB_88.o_Adel_f_GAACCTTC_S19_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_89" = "MATA_LB_JB_89.o_Adel_m_AGAGGATG_S20_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_90" = "MATA_LB_JB_90.y_K36_f_ACGCTTCT_S21_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_91" = "MATA_LB_JB_91.y_K36_m_CACAGGAA_S22_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_92" = "MATA_LB_JB_92.o_K36_f_ACGAATCC_S23_Aligned.sortedByCoord.out.bam",
                "Sample_MATA_LB_JB_93" = "MATA_LB_JB_93.o_K36_m_CCTTCCAT_S24_Aligned.sortedByCoord.out.bam"
  )

filteredCountTable_W_OUTLIER <- filteredCounts[,c(6:29)]

```

```{r}
# Read in sample info

filteredsampleInfo_W_OUTLIER <- read.csv("sample_info_W_OUTLIER.txt")

```

```{r}
# Check sample order

colnames(filteredCountTable_W_OUTLIER)
filteredsampleInfo_W_OUTLIER$run
all(filteredsampleInfo_W_OUTLIER$run == colnames(filteredCountTable_W_OUTLIER))

```

```{r}
### NO Interaction Model ####

filteredsampleInfo_W_OUTLIER_age_geno <- filteredsampleInfo_W_OUTLIER
age_geno <- factor(c("young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "young_K36R", "old_K36R", "old_K36R",
                  "young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "young_K36R", "old_K36R", "old_K36R",
                  "young_Adel", "young_Adel", "old_Adel", "old_Adel",
                  "young_K36R", "young_K36R", "old_K36R", "old_K36R")
                            )
filteredsampleInfo_W_OUTLIER_age_geno$age_geno <- age_geno

dds <- DESeqDataSetFromMatrix(countData = filteredCountTable_W_OUTLIER, colData = filteredsampleInfo_W_OUTLIER_age_geno, design = ~ sex + age_geno)
dds$age_geno = relevel(dds$age_geno, "young_Adel")
dds <- DESeq(dds)

```

```{r}
# Export normalized counts

normCounts <- counts(dds, normalized=T)
write.csv(as.data.frame(normCounts), 
          file = paste0("DESeq2_",currentDate,"_dm6_forStrand_noINT_wOUT_normCounts.csv"))

```

```{r}
# Export PCA: No Interaction Model w/ Outlier

vsd <- vst(dds, blind=FALSE)

pcaData <- plotPCA(vsd, intgroup=c("sex", "age_geno"), returnData=TRUE)
percentVar <- round(100* attr(pcaData, "percentVar"))

pdf(file = paste0("DESeq2_dm6_forStrand_noINT_wOUT_PCA_",currentDate,".pdf"),
    width = 9, 
    height = 6)

ggplot(pcaData, aes(PC1, PC2, color=age_geno, shape = sex)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"%variance"))+
  ylab(paste0("PC2: ",percentVar[2],"%variance"))+
  ggtitle("H3.3K36R and H3.3AΔ RNA-seq PCA - dm6 - noINT - wOUT") +
  geom_jitter()

dev.off()

```
